/*
 * definesPlataforma.h
 *
 *  Created on: 16/05/2013
 *      Author: clavelli
 */

#ifndef DEFINESPLATAFORMA_H_
#define DEFINESPLATAFORMA_H_

//IDs PARA EL PASAJE DE ESTRUCTURAS Y MENSAJES
#define HANDSHAKE 0
#define IPyPUERTO 1
#define ME_QUIERO_MOVER 3
#define DESTINO 3
#define PEDIR_INFO_NIVEL_PLAN 4
#define PEDIR_INSTANCIA 5
#define MOVIMIENTO_PERMITIDO 6
#define TURNO_CONCLUIDO 7
#define DATOS_DEL_NIVEL 9
#define DAR_RECURSO 10
#define DESCONEXION 11
#define JUEGO_TERMINADO 12
#define RESPUESTA_ORQUESTADOR 14
#define RECURSOS_LIBERADOS 15
#define RECURSOS_ASIGNADOS 16
#define RECURSOS_LIBRES 17
#define HAY_INTERBLOQUEO 18
#define RECURSOS_ASIGNADOS_CERO 19
#define RECURSOS_LIBRES_CERO 20
#define CONFIRMACION_DESCONEXION 21
#define SIGNAL_RECIBIDA 22

#define TRUE 1
#define FALSE 0


#endif /* DEFINESPLATAFORMA_H_ */
